"""Builds data/manuals/SAMSUNG_WASHER_FAULTS.md from an MIT-licensed Samsung washer fault table.

Source: github.com/perseus177/ha-samsung-washer-local, pinned to one commit and checked by hash, so a changed
upstream file can never slip in. The table is read as data with `ast` (never imported or executed). Its wording
is the project's own, not Samsung's (see the source's NOTICE); the MIT notice is kept in data/licenses/.

    uv run python -m scripts.ingest_samsung_faults
"""

import ast
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

REPO = "perseus177/ha-samsung-washer-local"
COMMIT = "b75ef1ee561de4426d2f150c81ce786169df2b3b"
TABLE_PATH = "custom_components/samsung_washer_local/const.py"
TABLE_SHA256 = "7d6d24833df1b4fd490ef77d256e5d1da02266ae3c163d7eef0acb7234184a6d"  # the reviewed copy
LICENSES_ALLOWED = {"MIT"}

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
OUT = DATA_DIR / "manuals" / "SAMSUNG_WASHER_FAULTS.md"
LICENSE_OUT = DATA_DIR / "licenses" / "ha-samsung-washer-local.LICENSE"
_SENTENCE_END = re.compile(r"(?<=[.!])\s+")


def _raw(path: str) -> bytes:
    with urllib.request.urlopen(f"https://raw.githubusercontent.com/{REPO}/{COMMIT}/{path}", timeout=30) as r:
        return r.read()


class _Constants(ast.NodeTransformer):
    """Replaces names such as `_SERVICE` with the string the module assigned to them, so literal_eval can read it."""

    def __init__(self, values: dict[str, str]) -> None:
        self.values = values

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if node.id not in self.values:
            raise ValueError(f"unexpected name in the fault table: {node.id}")
        return ast.copy_location(ast.Constant(self.values[node.id]), node)


def read_fault_table(source: str) -> list[tuple[tuple[str, ...], str, str]]:
    """The FAULT_MEANINGS rows: (codes, meaning, what to do)."""
    module = ast.parse(source)
    strings: dict[str, str] = {}
    table: ast.expr | None = None
    for node in module.body:
        target = (
            node.target
            if isinstance(node, ast.AnnAssign)
            else (node.targets[0] if isinstance(node, ast.Assign) else None)
        )
        if not isinstance(target, ast.Name) or node.value is None:
            continue
        if target.id == "FAULT_MEANINGS":
            table = node.value
        elif isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            strings[target.id] = node.value.value
    if table is None:
        raise ValueError("FAULT_MEANINGS not found")
    rows = ast.literal_eval(_Constants(strings).visit(table))
    return [(tuple(codes), meaning, action) for codes, meaning, action in rows]


def to_markdown(rows: list[tuple[tuple[str, ...], str, str]]) -> str:
    lines = [
        "---",
        "model_id: SAMSUNG-WASHER",
        "family: washer",
        "scope: family",
        "citation: Samsung washer fault codes",
        f"title: Samsung washer fault codes (from {REPO}@{COMMIT[:7]}, MIT)",
        "---",
        "",
        f"<!-- Generated by scripts/ingest_samsung_faults.py from {REPO}@{COMMIT}. Do not edit by hand. -->",
    ]
    for codes, meaning, action in rows:
        spellings = list(dict.fromkeys(c.upper() if len(c) <= 4 else c for c in codes))  # "DrumClean" stays readable
        head, also = spellings[0], spellings[1:]
        lines += ["", f"## {head} {meaning}", f"{meaning}."]
        if also:
            lines.append(f"Also shown as: {', '.join(also)}")
        steps = [s.strip() for s in _SENTENCE_END.split(action) if s.strip()]
        lines += [f"{i}. {step}" for i, step in enumerate(steps, 1)]
    return "\n".join(lines) + "\n"


def main() -> None:
    license_text = _raw("LICENSE").decode()
    if not any(license_text.startswith(f"{name} License") for name in LICENSES_ALLOWED):
        sys.exit("refusing: the source licence is not on the allowlist")
    table = _raw(TABLE_PATH)
    digest = hashlib.sha256(table).hexdigest()
    if digest != TABLE_SHA256:
        sys.exit(f"refusing: {TABLE_PATH} changed (sha256 {digest}); review it, then update TABLE_SHA256")
    rows = read_fault_table(table.decode())
    OUT.write_text(to_markdown(rows), encoding="utf-8", newline="\n")
    LICENSE_OUT.parent.mkdir(exist_ok=True)
    LICENSE_OUT.write_text(license_text, encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} faults ({sum(len(c) for c, _, _ in rows)} codes) to {OUT.name}")


if __name__ == "__main__":
    main()
